# Generated by Django 2.1.7 on 2019-03-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190326_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Client',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
